print("-----------------")
print("****    Sum()    ****")
print("-----------------")
lst2 = [1,2,3,4,5,10,9,7,8,6]
print(sum(lst2))
print("-----------------")
print("****    Min()    ****")
print("-----------------")
print(min(lst2))
print("-----------------")
print("****    Max()    ****")
print("-----------------")
print(max(lst2))
print("-----------------")
print("**** Sort()In Ascending Default ****")
print("-----------------")
lst2.sort()
print(lst2)
print("-----------------")
print("**** Sort()In Descending ****")
print("-----------------")
lst2.sort(reverse=True)
print(lst2)
print("-----------------")
print("**** Conversion Of List Into Tuple ****")
print("-----------------")
t1=tuple(lst2)
print("list : ",lst2)
print("tuple: ",t1)
print("-----------------")
print("****     Delete Or Deletion     ****")
print("-----------------")
lst2.__delitem__(1)
print(lst2)